### ISSUE TITLE
No image rendered

### ISSUE THREAD

**Issue by dietantejensen** [websightgmbh/typo3-ws_textmedia_bootstrap#1]
System: 7.6.3, with bootstrap_core an bsdist installed (so the first question would be: do they clash?). These extensions don't come with a text&media element, so your extension was warmly welcomed.

However, it doesn't work.
- in replace mode there's the yellow warning "content element is not defined"
- in standalone mode, no image is rendered, and when I try to create a new content element, there is none to chose from.

Did I miss something?

**Comment by cedricziel** [comment]
Unfortunately i can only speculate. bootstrap_core uses (as far as i can see) css_styled_content which would definitely clash, as the official documentation states that both in the same root typoscript template wouldnt work. (You would also need to migrate the old csc fields to the new fcc fields with the install tool wizard, but be warned - this is a one-way road).

I would advise you to change switch from CSC to FCC anyways if the project is in an early state or being upgraded.

I hope that helps. - I'll close this now, but please keep asking if you have _any_ questions.
