### ISSUE TITLE
suggestion: adding class="img-responsive" to img-tag

### ISSUE THREAD

**Issue by Karionis** [websightgmbh/typo3-ws_textmedia_bootstrap#8]
Hello,

one suggestion: Wouldn't it be better to have the possibility to add the class="img-responsive" to the image tag, because this is the class intended to make images responsive with Bootstrap 3. If there is no such class and the content is displayed on a desktop device the large image isn't scaled to the available space and is visually cropped to overflow: hidden.

HTH

Karionis

**Comment by cedricziel** [comment]
Hi @Karionis !

We added the class already, but there's a change pending in https://github.com/alexanderschnitzler/fluid-styled-responsive-images that resolves a the issue that attributes are not emitted through the media viewhelper.

I opened a ticket and I'm pretty sure Alex will respond soon :)

alexanderschnitzler/fluid-styled-responsive-images#14

**Comment by cedricziel** [comment]
Amendum: You can clone the develop branch of fluid_styled_responsive_images that contains the fix.

**Comment by alexanderschnitzler** [comment]
Just released a new version.
https://typo3.org/extensions/repository/view/fluid_styled_responsive_images

**Comment by cedricziel** [comment]
Thanks a bunch, Alex!
